### ISSUE TITLE
Use createTicket mutation instead of addContact mutation to capture article feedback

### ISSUE THREAD

**Issue by breezyboa** [bigbinary/acehelp#190]
Currently, article feedback is being captured using the addContact mutation.
This needs to be changes and new mutation "createTicket" needs to be used instead

**Comment by neerajdotname** [comment]
There is more to this issue.

The whimsical diagram mentioned at https://github.com/bigbinary/acehelp/issues/147says that email is an optional field and the behavior of the application changes if email is entered or not.

If email is entered then create a ticket. Otherwise create a feedback for that article.
