### ISSUE TITLE
Still not able to create an organization

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#561]
https://monosnap.com/file/fHR3YScoxikxm3AQ71BAEosUtK3AHb

**Comment by tejaswinichile** [comment]
Seems this changes has been removed : https://github.com/bigbinary/acehelp/pull/538/files

**Comment by tejaswinichile** [comment]
@neerajdotname Fixed this issue on staging, please check.
@ritesh404 Can you check https://github.com/bigbinary/acehelp/blame/master/app/javascript/Admin/Main.elm#L730 not assigning `userId` to updated model

**Comment by neerajdotname** [comment]
If an organization was created with either missing user_id or invalid user_id then that should have raised a foreign_key violation. Please create an issue to add proper foreign_key.

**Comment by neerajdotname** [comment]
@tejaswinichile Please do not link to the live code. It gets outdated. Refer to https://how-we-work.bigbinary.com/github/hit-y-before-copying-url-from-github.html

**Comment by neerajdotname** [comment]
The fix worked. I was able to create an organization.

**Comment by tejaswinichile** [comment]
@neerajdotname We do have the foreign key, but the error we are rendering is not a server-side error.
We have the fix for this in #528 to render proper errors.

**Comment by ritesh404** [comment]
@tejaswinichile the reason It might not be gettings assigned a value might be because in line 763
https://github.com/bigbinary/acehelp/blob/de028fb19a880c2aade8fc2d3028f974f6c96267/app/javascript/Admin/Main.elm#L763
 the case expression must have satisfied the default case rather than matching `OrganizationCreate `.
Anyway, looks like you have already fixed the issue. Hence closing
