### ISSUE TITLE
Trix editor should be more friendly to type at the bottom

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#628]
One can experiment with how basecamp handles such cases.

https://www.useloom.com/share/ae53d8a980b843e2bcdc1d4ae0b51113

**Comment by vishaltelangre** [comment]
@neerajdotname @ritesh404 

The height of the Trix editor integrated into Basecamp dynamic, that is it depends on the size of the contents inside the editor.

I think that's a better default than trying to fit the whole editor into the visible viewport having the fixed width-height dimensions. With the default settings, the editor does not have its own scrollbar since it expands the page itself vertically with the contents inside it.

I am going to assign this to myself and work adding some space between the editor and the bottom of the page to reduce the visual confusion.

If it doesn't work out as expected, we will try to display the editor into a container with the fixed dimensions and also with vertical scrollbars of its own.

@vishaltelangre _a

**Comment by neerajdotname** [comment]
https://www.useloom.com/share/5d3f4e6ae0004a1e99177d97cabac3ba

**Comment by vishaltelangre** [comment]
Fixed in #631.
