### ISSUE TITLE
Ability to delete the uploaded files permanently from the editor

### ISSUE THREAD

**Issue by tejaswinichile** [bigbinary/acehelp#668]
https://3.basecamp.com/3091787/buckets/9258656/todos/1326766710

**Comment by vishaltelangre** [comment]
@chiraggshah Since the backend endpoint is ready, you can take this up. On "trix-attachment-remove" event, we can issue a DELETE request to that endpoint. The `id` of the attachment can be retrieved using `attachment.attributes.id` which we store like this https://github.com/bigbinary/acehelp/pull/674.

**Comment by neerajdotname** [comment]
Let’s assign contextual hrlpbrealtex tasks to Tejaswini. Chirag should be assigned ticketing work which is low priority tasks.

**Comment by vishaltelangre** [comment]
Sure, @neerajdotname. 

@chiraggshah Please ignore the above message. I or Tejaswini will take care of this.
