### ISSUE TITLE
Staging is not showing any articles

### ISSUE THREAD

**Issue by vipulnsward** [bigbinary/acehelp#73]
@breezyboa _a

**Comment by vipulnsward** [comment]
Please work with @piyushtiw on this

**Comment by breezyboa** [comment]
@piyushtiw _a looks like this is a CORS issue
can you look into it?

https://monosnap.com/file/z0La9i5IXUtbZSrFgeZJLPEbZI6hGh

**Comment by rkr090** [comment]
It looks like this is still not working even after #80 

It might not be a http/https regex issue because it is also not working on the review app for PR #79 ( before PR #80 ) even if we access it with https scheme.

https://acehelp-staging-pr-79.herokuapp.com/

<img width="640" alt="learn academy 2018-06-08 16-15-12" src="https://user-images.githubusercontent.com/2760306/41154860-2d0e8c86-6b39-11e8-881f-73e7a9165182.png">
